# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

app-image: &app-image circleci/ruby:2.5.3-node
app-env: &app-env
  BUNDLE_PATH: vendor/bundle

version: 2
jobs:
  build:
    docker:
      - image: *app-image
        environment:
          <<: *app-env

    steps:
      - checkout

      - run:
          name: Make sure Ruby versions match
          command: test "$(ruby -v | sed 's/^ruby \([0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\).*/\1/')" = "$(cat .ruby-version)"

      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Install latest gem dependencies
          command: bundle update

      - run:
          name: Run rubocop
          command: bundle exec rake rubocop

      - run:
          name: Run rubocop-git
          command: bundle exec rake rubocop_git
