AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/*.pb.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'spec/dummy/db/schema.rb'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

# TODO re-enable once they fixed the issue where a multi key-value #merge! also gets rewritten
Performance/RedundantMerge:
  Enabled: false

# TODO: re-enable once upstream bug is fixed
# See https://github.com/nevir/rubocop-rspec/issues/62
RSpec/FilePath:
  Enabled: false

# Enable cops that are inactive by default:

Style/SymbolArray:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

# Don't restrict some cops to certain directories:

Rails/FindBy:
  Include: null

Rails/FindEach:
  Include: null
