AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/*.pb.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'client/**/*'
    - 'spec/dummy/db/schema.rb'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  EnforcedStyle: flexible

Rails/Date:
  EnforcedStyle: flexible

RSpec/DescribeClass:
  Enabled: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Rails/SafeNavigation:
  ConvertTry: true

# TODO: Cop is currently broken for `foo_bar1`. Re-enable once fixed.
# See https://github.com/bbatsov/rubocop/issues/3516
Style/VariableNumber:
  Enabled: false

# Some RSpec cops are a bit excessive

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

# Enable cops that are inactive by default:

Style/SymbolArray:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Rails/SaveBang:
  Enabled: true

# Don't restrict some cops to certain directories:

Rails/FindBy:
  Include: null

Rails/FindEach:
  Include: null
