AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/*.pb.rb'
    - '**/*_pb.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'client/**/*'
    - 'spec/dummy/db/schema.rb'
    - '**/node_modules/**/*'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  EnforcedStyle: flexible

Rails/Date:
  EnforcedStyle: flexible

RSpec/DescribeClass:
  Enabled: false

Performance/RedundantMerge:
  MaxKeyValuePairs: 1

Rails/SafeNavigation:
  ConvertTry: true

# TODO: Cop is currently broken for `foo_bar1`. Re-enable once fixed.
# See https://github.com/bbatsov/rubocop/issues/3516
Naming/VariableNumber:
  Enabled: false

# Some RSpec cops are a bit excessive

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

# Enable cops that are inactive by default:

Style/SymbolArray:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringMethods:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/SkipsModelValidations:
  Blacklist:
    # - update_all
    - decrement!
    - decrement_counter
    - increment!
    - increment_counter
    - toggle!
    - touch
    - update_attribute
    - update_column
    - update_columns
    - update_counters

# Don't restrict some cops to certain directories:

Rails/FindBy:
  Include: null

Rails/FindEach:
  Include: null

# brakeman currently cannot parse squiggly heredocs(i.e. <<~DOC)
Layout/IndentHeredoc:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
