AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 18.11

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

# Enable cops that are inactive by default:

Style/ExtraSpacing:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
